version: '3'

services:
    db:
        image: mongo
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: expo-testing
        ports:
            - "27017:27017"
        command: --quiet
    web:
        build:
            context: ./api
        volumes:
            - ./api:/app
        depends_on:
            - db
        ports:
            - "8000:8000"
        links:
            - db:db
        command: gunicorn -b 0.0.0.0:8000 server:app  --capture-output
